spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_system?useSSL=false
    username: bankUser
    password: password

  jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true

accountnumber:
              start: 500000000000

encryption:
            password: supersecurepsw
            salt: 1234567890ABCDEF

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}